user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events { worker_connections 1024; }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format json_combined escape=json
        '{"time":"$time_iso8601","remote_addr":"$remote_addr","method":"$request_method",'
        '"uri":"$request_uri","status":$status,"bytes_sent":$bytes_sent,'
        '"request_time":$request_time,"upstream_response_time":"$upstream_response_time",'
        '"service":"aviondash-web","env":"demo"}';
    access_log /var/log/nginx/access.log json_combined;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
    include /etc/nginx/conf.d/*.conf;
}
